### ISSUE TITLE
Duplicate entry exception when moving entry to notifications_history

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-commons#6]
`at org.killbill.queue.DBBackedQueue.moveEntryToHistoryFromTransaction(DBBackedQueue.java:370)`

**Comment by sbrossie** [comment]
Re-opened as we are not sure this is the root cause of that problem; will close it if the issue disappears.

**Comment by galenp** [comment]
I haven't been running KB on my local box in some weeks since i've pushed it to a dockerised AWS/EC2 set up where the console output is not directly on my screen.

If i recall tho... I had a 'feeling' that this error may have been related to a poor shutdown of the app... like a power-off. Then when the app was restarted some routine queue processor kept on failing every couple of minutes with the above output.

**Comment by sbrossie** [comment]
It is true that when we have the system configured to use multiple threads, there is a race at startup time to fetch the existing entries, and so if indeed we had a synchronization bug here, that could explain it.

**Comment by pierre** [comment]
It looks like MySQL can also reset the column for us (see for instance http://bugs.mysql.com/bug.php?id=18274). Just pushed a proposed fix.

**Comment by sbrossie** [comment]
The issue is that mysql resets the auto_increment when it restarts (the auto_increment is only kept in memory: see http://stackoverflow.com/questions/8112685/auto-increment-get-resetted-to-0-at-every-service-restart). Since we move entries from bus_events to bus_events_history, then, when mysql restarts, it sees an auto_increment of 0, and bus_events entries cannot be moved to the bus_events_history, leading to a lot of 'IN_PROCESSING' entries.

**Comment by pierre** [comment]
Tables all use auto-increment nowadays.
